catalogs:
    default:
        "@commitlint/cli": ^20.2.0
        "@commitlint/config-conventional": ^20.2.0
        "@commitlint/cz-commitlint": ^20.2.0
        "@eslint/js": ^9.39.2
        "@tailwindcss/vite": ^4.1.18
        "@tanstack/eslint-plugin-query": ^5.91.2
        "@tanstack/eslint-plugin-router": ^1.141.0
        "@types/node": ^25.0.2
        "@types/react": ^19.2.7
        "@types/react-dom": ^19.2.3
        "@vitejs/plugin-react": ^5.1.2
        babel-plugin-react-compiler: ^1.0.0
        class-variance-authority: ^0.7.1
        clsx: ^2.1.1
        commitizen: ^4.3.1
        eslint: ^9.39.2
        eslint-plugin-react: ^7.37.5
        eslint-plugin-react-compiler: 19.1.0-rc.2
        eslint-plugin-react-hooks: ^7.0.1
        eslint-plugin-react-refresh: ^0.4.24
        globals: ^16.5.0
        husky: ^9.1.7
        inquirer: ^9.3.8
        lint-staged: ^16.2.7
        lucide-react: ^0.561.0
        prettier: ^3.7.4
        prettier-plugin-prisma: ^5.0.0
        react: ^19.2.3
        react-dom: ^19.2.3
        tailwind-merge: ^3.4.0
        tailwindcss: ^4.1.18
        tw-animate-css: ^1.4.0
        typescript: ^5.9.3
        typescript-eslint: ^8.49.0
        vite: ^7.2.7
        vite-tsconfig-paths: ^5.1.4
